version: '3.8'

services:
  web:
    image: python:3.9
    container_name: django-container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
