# Generated by Django 5.1.5 on 2025-02-01 04:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_rename_question_bn_faq_question_be_alter_faq_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='question_be',
            new_name='question_bn',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
