# Generated by Django 5.1.5 on 2025-02-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_rename_question_be_faq_question_bn_alter_faq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
    ]
